[package]
name = "pratt"
authors = ["Lucas Newcomb <lucasnewcomb721@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.4.5"
rust-ini = "0.18"
tensorflow = "0.19.1"